name: Deploy # Nombre del flujo de trabajo

on: push # Ejecutar el flujo cuando haya un push al repositorio

jobs: # Lista de trabajos que se ejecutarán
  build: # Primer trabajo: construcción
    runs-on: ubuntu-latest # El entorno donde correrá (una VM de Ubuntu)
    steps: # Lista de pasos que se ejecutarán en orden
      - name: Checkout code # Paso 1: Obtener el código del repositorio
        uses: actions/checkout@v4

      - name: Install node # Paso 2: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Especificar la versión de Node

      - name: Install dependencies # Paso 3: Instalar dependencias del proyecto
        run: npm install

      - name: Run tests # Paso 4: Ejecutar pruebas automáticas
        run: npm run test

      - name: Build project # Paso 5: Construir el proyecto
        run: npm run build

      - name: Upload artifact # Paso 6: Subir los archivos a desplegar
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/ # Carpeta que contiene los archivos estáticos

  deploy: # Segundo trabajo: despliegue
    runs-on: ubuntu-latest
    needs: build # Este job depende de que 'build' se complete
    permissions: # Permisos requeridos por el job para operar
      pages: write # Permiso para escribir en GitHub Pages
      id-token: write # Permiso para autenticación segura
    environment: # Define el entorno de despliegue
      name: github-pages # Nombre del entorno
      url: ${{ steps.deploy-pages.outputs.page_url }} # URL de la página publicada
    steps:
      - name: Deploy to pages # Paso único: desplegar en GitHub Pages
        id: deploy-pages
        uses: actions/deploy-pages@v4